table PayType
	lineageTag: 91a343c8-2f75-41ad-a018-9275a2e2b794

	column PayTypeID
		dataType: string
		isHidden
		lineageTag: 1034f6dc-57f9-4611-9c26-c9c090f8ea54
		summarizeBy: none
		sourceColumn: PayTypeID

		annotation SummarizationSetBy = Automatic

	column PayType
		dataType: string
		lineageTag: 64f662eb-93f9-496a-a95f-65f9d277ca5d
		summarizeBy: none
		sourceColumn: PayType

		annotation SummarizationSetBy = Automatic

	partition PayGroup = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="select distinct PayTypeID, [Hrly-Salaried] PayType#(lf)from [HR].[PayGroup]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"PayTypeID", "PayTypeID"}, {"PayType", "PayType"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"PayTypeID", type text}, {"PayType", type text}})
				in
				    #"Changed Type"

