table SeparationReason
	lineageTag: 85b289cb-4757-434f-948d-42912318e2bb

	column SeparationTypeID
		dataType: string
		isHidden
		lineageTag: 779c6021-160a-4e71-b2be-5b894fa76ab9
		summarizeBy: none
		sourceColumn: SeparationTypeID

		annotation SummarizationSetBy = Automatic

	column SeparationReason
		dataType: string
		lineageTag: b44a63f1-229e-4a8f-bf90-eb63822e2c80
		summarizeBy: none
		sourceColumn: SeparationReason

		annotation SummarizationSetBy = Automatic

	partition TermReason = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT distinct SeparationTypeID, [Vol-Invol] SeparationReason#(lf)  FROM [IP].[HR].[TermReason]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"SeparationTypeID", "SeparationTypeID"}, {"SeparationReason", "SeparationReason"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"SeparationTypeID", type text}, {"SeparationReason", type text}})
				in
				    #"Changed Type"

