table BU
	lineageTag: 89ca23e1-674c-4ab0-96bd-f20677113e1f

	measure 'Count of BU' = COUNTA('BU'[BU])
		lineageTag: 1134fd8b-d59c-47d6-8a65-a419847617bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		lineageTag: 779dd929-d123-4ee5-905f-8ed5287806c6
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column RegionSeq
		dataType: string
		lineageTag: e0c1c9a2-142a-4222-81cd-b3801599e054
		summarizeBy: none
		sourceColumn: RegionSeq

		annotation SummarizationSetBy = Automatic

	column VP
		dataType: string
		lineageTag: 5686d7fb-ad68-4850-b926-62a8dbb1803e
		summarizeBy: none
		sourceColumn: VP

		annotation SummarizationSetBy = Automatic

	column Region = mid([RegionSeq], 3,15)
		lineageTag: ebbda8e0-2c05-496a-9cea-e9d3b09a69dc
		summarizeBy: none
		sortByColumn: RegionSeq

		annotation SummarizationSetBy = Automatic

	partition BU = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="select distinct market BU,#(lf)  REGIONTITLE Region,#(lf)  MARKETDIRECTOR VP#(lf)from hr.bu"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"BU", "BU"}, {"Region", "RegionSeq"}, {"VP", "VP"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"BU", type text}, {"RegionSeq", type text}, {"VP", type text}})
				in
				    #"Changed Type"

