table Date
	lineageTag: 3c20188a-a3b3-4d8c-a2ac-0fe7dce040cb
	dataCategory: Time

	measure 'Count of Date' = COUNTA('Date'[Date])
		lineageTag: d424a501-fe57-46c0-b0ed-ba65d9d40817

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 7c140958-6aa7-4ec1-8d02-480ed922dd29
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 0f809af4-d31b-4977-a214-8f13fa42f41d
			defaultHierarchy: LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 153dce9c-c865-404e-a361-a891f75bdfb9
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		lineageTag: ac4e7cc3-6280-4386-9695-de8720273f8d
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: string
		lineageTag: ee57b12c-c80c-491e-a4c1-e150850c7924
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

	column PeriodNumber
		dataType: int64
		lineageTag: a6f066e4-a4e9-4d2e-9b39-08f424671374
		summarizeBy: sum
		sourceColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qtr
		dataType: int64
		lineageTag: 5c1f8e60-f1ff-49e2-98a5-14984e991664
		summarizeBy: sum
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QtrNumber
		dataType: string
		lineageTag: 3f8afca2-c26d-4624-b9ea-1e5b584b6a19
		summarizeBy: none
		sourceColumn: QtrNumber

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2417645f-4ede-48d0-9b79-c7f2a8c22327
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: int64
		lineageTag: 47615e8e-f2ab-47f1-a8f7-5223d34e4790
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5bc280b2-3cfc-4357-ae10-a64038e6533a
		summarizeBy: none
		sourceColumn: MonthStartDate

		variation Variation
			isDefault
			relationship: f496f9ad-5665-4785-a30e-b1bbcf7be215
			defaultHierarchy: LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MonthEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 966f7e60-947a-42fe-9b32-ef1c2ba56088
		summarizeBy: none
		sourceColumn: MonthEndDate

		variation Variation
			isDefault
			relationship: b2a9d346-0212-432d-a1a9-57680b4a73ea
			defaultHierarchy: LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MonthIncrementNumber = ([Year]-MIN([Year]))*12 +[MonthNumber]
		isHidden
		lineageTag: 01c651f7-6477-433d-90f5-f0e1fbdefe10
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy YQM
		lineageTag: 707a6be5-aa57-49eb-aed7-873f3ec99d83

		level Year
			lineageTag: e6f669c8-e083-4c66-a932-64f037acc45b
			column: Year

		level QtrNumber
			lineageTag: 7ff9d907-d13a-43e8-890f-c82012d18861
			column: QtrNumber

		level PeriodNumber
			lineageTag: fee359b2-4104-4e51-9186-0e83643ee86b
			column: PeriodNumber

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [HR].[Date].*   FROM [HR].[Date]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date"}, {"Month", "Month"}, {"MonthNumber", "MonthNumber"}, {"Period", "Period"}, {"PeriodNumber", "PeriodNumber"}, {"Qtr", "Qtr"}, {"QtrNumber", "QtrNumber"}, {"Year", "Year"}, {"Day", "Day"}, {"MonthStartDate", "MonthStartDate"}, {"MonthEndDate", "MonthEndDate"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type datetime}, {"Month", type text}, {"MonthNumber", Int64.Type}, {"Period", type text}, {"PeriodNumber", Int64.Type}, {"Qtr", Int64.Type}, {"QtrNumber", type text}, {"Year", Int64.Type}, {"Day", Int64.Type}, {"MonthStartDate", type datetime}, {"MonthEndDate", type datetime}})
				in
				    #"Changed Type"

	annotation __PBI_LegacyCustomDateTable = true

