table Employee
	isHidden
	lineageTag: 1818a90f-9c42-466c-b63c-a1a7c51474dd

	measure EmpCount = CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])))
		formatString: #,0
		lineageTag: c0e6d18c-c307-4b0a-b2e3-bffc62fab2ea

	measure Seps = CALCULATE(COUNT([EmplID]), FILTER(Employee, NOT(ISBLANK(Employee[TermDate]))))
		formatString: #,0
		lineageTag: 8252214a-19e7-474e-8e2c-fb134271afd5

	measure Actives = CALCULATE([EmpCount], FILTER(Employee, ISBLANK(Employee[TermDate])))
		formatString: #,0
		lineageTag: 41b11325-9418-467a-8cd3-b43dde891c64

	measure 'New Hires' = SUM([isNewHire])
		formatString: #,0
		lineageTag: 1b3d9292-b51f-48f0-8908-aef8d3cbd8f9

	measure 'AVG Tenure Days' = AVERAGE([TenureDays])
		formatString: #,0
		lineageTag: a72d32ed-c4fe-4e77-b5ab-912a9b0b46ea

	measure 'AVG Tenure Months' = ROUND([AVG Tenure Days]/30, 1)-1
		formatString: 0
		lineageTag: 39677f32-3330-4b71-af0b-b4fbc18788c0

	measure 'AVG Age' = ROUND(AVERAGE([Age]), 0)
		lineageTag: 2fb5574d-6469-4d67-b9fb-d5fdf2accc84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum of BadHires' = SUM([BadHires])
		formatString: #,0
		lineageTag: 73228d63-8f76-48b4-96cc-1e71afe43b4f

	measure 'New Hires SPLY' = CALCULATE([New Hires],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		lineageTag: af2466c4-db1b-44d9-adf4-ebb6c24a1635

	measure 'Actives SPLY' = CALCULATE([Actives],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		lineageTag: e8060931-9e92-484c-8f9b-6113868ad6c2

	measure 'Seps SPLY' = CALCULATE([Seps],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		lineageTag: 5ae5842c-f2c6-4963-8f9b-ea98babc719b

	measure 'EmpCount SPLY' = CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])),SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		lineageTag: 7cf8da84-faca-4ef9-8a2b-4f611a13b0ef

	measure 'Seps YoY Var' = [Seps]-[Seps SPLY]
		formatString: #,0
		lineageTag: 8741f3d5-d3e5-4193-98fd-58bf3de584f1

	measure 'Actives YoY Var' = [Actives]-[Actives SPLY]
		formatString: #,0
		lineageTag: 12aa4de4-5700-4ad9-a09e-2103e225b933

	measure 'New Hires YoY Var' = [New Hires]-[New Hires SPLY]
		formatString: #,0
		lineageTag: 71b00be1-c075-40ec-b38d-fd1f0a8b1e7d

	measure 'Seps YoY % Change' = DIVIDE([Seps YoY Var], [Seps SPLY])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 0c32c220-6132-49be-b200-bbd6d525d417

	measure 'Actives YoY % Change' = DIVIDE([Actives YoY Var], [Actives SPLY])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: a59107cc-09e7-456a-8cda-96cb43f19bb2

	measure 'New Hires YoY % Change' = DIVIDE([New Hires YoY Var], [New Hires SPLY])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: cbadb500-3ce8-4f60-b9d7-fe8fd36b0a72

	measure 'Bad Hires SPLY' = CALCULATE([Sum of BadHires],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		lineageTag: 398e1f76-232b-4034-b456-3d37e213aabc

	measure 'Bad Hires YoY Var' = [Sum of BadHires]-[Bad Hires SPLY]
		formatString: #,0
		lineageTag: 855c73f5-fc84-4f5a-afa7-0cbccf4b6359

	measure 'Bad Hires YoY % Change' = DIVIDE([Bad Hires YoY Var], [Bad Hires SPLY])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: a104ec96-7d96-4bda-b891-6dcbc9babb6d

	measure 'TO %' = DIVIDE([Seps], [Actives])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0c409527-1e68-4e11-b023-ecb3171cc69c

	measure 'TO % Norm' = CALCULATE([TO %], all(Gender[Gender]), ALL(Ethnicity[Ethnicity]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e0dc8121-3435-4208-8813-b17b39d7109e

	measure 'TO % Var' = [TO %]-[TO % Norm]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 28237fe1-8ec5-4197-a8b5-54f466b7650e

	measure Sep%ofActive = DIVIDE([Seps],[Actives])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0c7189b-3a51-4a50-aa85-56cdf53b93af

	measure Sep%ofSMLYActives = DIVIDE([Seps SPLY],[Actives SPLY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2be9e6c1-883f-4726-90b3-6df416274772

	measure BadHire%ofActives = DIVIDE([Sum of BadHires],[Actives])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 01502d39-b9ab-4629-973b-0475c9871dd5

	measure BadHire%ofActiveSPLY = DIVIDE([Bad Hires SPLY],[Actives SPLY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bf579414-9f62-4a1d-a5fc-f696a75d1fe3

	column date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: da8347f2-6b7d-48bf-9705-4a373ea262ad
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column EmplID
		dataType: int64
		isHidden
		lineageTag: 46015b02-5523-4cde-afe6-6911648aeb25
		summarizeBy: count
		sourceColumn: EmplID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gender
		dataType: string
		isHidden
		lineageTag: 3fbae66d-07dd-42a8-9a0a-c77e74b17fad
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		isHidden
		lineageTag: 9122e7f0-3be6-41e9-9ddc-e789a93f016e
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EthnicGroup
		dataType: string
		isHidden
		lineageTag: 522079dc-ae62-4383-bef1-11b56c439439
		summarizeBy: none
		sourceColumn: EthnicGroup

		annotation SummarizationSetBy = Automatic

	column FP
		dataType: string
		isHidden
		lineageTag: c66260cc-f080-4774-b981-9b4ac29f2cfe
		summarizeBy: none
		sourceColumn: FP

		annotation SummarizationSetBy = Automatic

	column TermDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: f0ced92e-ca81-465a-adc7-56cc8cd7d659
		summarizeBy: none
		sourceColumn: TermDate

		variation Variation
			isDefault
			relationship: e020e64e-e74a-4b8f-bed8-e879143ea6d8
			defaultHierarchy: LocalDateTable_cc28ef26-f63a-4bc3-b357-93ab34cd6d9b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column isNewHire = IF(YEAR([date]) = YEAR([HireDate]) && MONTH([date])=MONTH([HireDate]), 1)
		isHidden
		lineageTag: 6ac8c542-152e-4495-9ad9-1af807c29b39
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		isHidden
		lineageTag: 0ad404f9-8ce2-4e6e-b7e7-205d85552520
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		isHidden
		lineageTag: ca268af8-63a0-4dc1-af60-a90bf336bb63
		summarizeBy: none
		sourceColumn: HireDate

		variation Variation
			isDefault
			relationship: 3e454a13-2d74-4769-b44d-91ce492acf1a
			defaultHierarchy: LocalDateTable_c04ce649-6e25-466f-9bbc-faabfec0fe29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PayTypeID
		dataType: string
		isHidden
		lineageTag: 7a437a37-75c8-4b8c-9110-c3c64fe514bd
		summarizeBy: none
		sourceColumn: PayTypeID

		annotation SummarizationSetBy = Automatic

	column TermReason
		dataType: string
		isHidden
		lineageTag: 8bacadd7-5472-48cc-b4cc-5598637d3c7f
		summarizeBy: none
		sourceColumn: TermReason

		annotation SummarizationSetBy = Automatic

	column AgeGroupID = IF([Age]<30, 1, IF([Age]<50, 2, 3))
		isHidden
		lineageTag: 74acfceb-16bf-4068-9dde-7c3ea2dc8fa3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TenureDays = IF([date]-[HireDate]<0,[HireDate]-[date],[date]-[HireDate])
		dataType: double
		isHidden
		lineageTag: 5ac6ad06-5d51-47cf-86c0-4f816510ad64
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TenureMonths = CEILING([TenureDays]/30, 1) -1
		isHidden
		lineageTag: b0ad6a54-5334-4abf-8f24-dd3e89f4fdd3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BadHires = IF(OR((([HireDate]-[TermDate])*-1)>=61,ISBLANK([TermDate])),0,1)
		dataType: double
		lineageTag: 1df76a6a-6e28-4ca2-b5ee-d16eb0402a97
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Employee = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT dateadd(year, 1, d.date) Date#(lf)  ,Market BU#(lf)  ,[EmplID]#(lf)  ,iif([Gender]='M', 'C', 'D') Gender --  ,iif([Gender]='M', 'F', 'M') Gender#(lf)  ,[Age] - (2013 - year(d.date)) Age#(lf)  ,[EthnicGroup]#(lf)  ,[FP]#(lf)  ,dateadd(year, 1, [SenDate]) HireDate#(lf)  ,p.PayTypeID#(lf)  ,null [TermDate]#(lf)  ,null [TermReason]#(lf) FROM [IP].[HR].[AllEmps] E , [HR].[Date] d , [HR].[BU] b , hr.PayGroup p --, hr.TermReason t#(lf) where d.day = 1 and e.SenDate <= d.MonthEndDate and isnull(e.termdate, '9999-01-01') >= d.MonthEndDate and d.Date < '2014-01-01'#(lf)  and p.PayGroup = e.PayGroup#(lf)  and b.UNIT = e.Unit and [EmplID] % 2 = 0#(lf)union all#(lf)--seps#(lf)SELECT dateadd(year, 1, d.date) Date#(lf)    ,Market BU#(lf)      ,[EmplID]#(lf)      ,iif([Gender]='M', 'C', 'D') Gender#(lf)      ,[Age] - (2013 - year(d.date)) Age#(lf)      ,[EthnicGroup]#(lf)      ,[FP]#(lf)      ,dateadd(year, 1,[SenDate]) HireDate#(lf)      ,p.PayTypeID#(lf)      ,dateadd(year, 1, [TermDate]) [TermDate]#(lf)      ,t.[SeparationTypeID] [TermReason]#(lf)  FROM [IP].[HR].[AllEmps] E, [HR].[Date] d , [HR].[BU] b, hr.PayGroup p , hr.TermReason t#(lf) where d.day = 1 and e.TermDate <= d.MonthEndDate and e.TermDate >= d.MonthStartDate and d.Date < '2014-01-01'#(lf)  and p.PayGroup = e.PayGroup #(lf)  and t.[Term-Discharge]= e.[Term-Discharge]#(lf)  and b.UNIT = e.Unit and [EmplID] % 2 = 0"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"date", "date"}, {"EmplID", "EmplID"}, {"Gender", "Gender"}, {"Age", "Age"}, {"EthnicGroup", "EthnicGroup"}, {"FP", "FP"}, {"TermDate", "TermDate"}, {"BU", "BU"}, {"HireDate", "HireDate"}, {"PayTypeID", "PayTypeID"}, {"TermReason", "TermReason"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"date", type datetime}, {"EmplID", Int64.Type}, {"Gender", type text}, {"Age", Int64.Type}, {"EthnicGroup", type text}, {"FP", type text}, {"TermDate", type datetime}, {"BU", type text}, {"HireDate", type datetime}, {"PayTypeID", type text}, {"TermReason", type text}})
				in
				    #"Changed Type"

