table FP
	lineageTag: 99a5924f-9aa6-4fd8-b3f0-f2110ea2f56e

	column FP
		dataType: string
		lineageTag: 8e107760-5318-45fe-8f90-a1a8e3e9aa0e
		summarizeBy: none
		sourceColumn: FP

		annotation SummarizationSetBy = Automatic

	column FPDesc
		dataType: string
		lineageTag: 85394144-f60a-45a6-ade4-e975ebda1ba4
		summarizeBy: none
		sourceColumn: FPDesc

		annotation SummarizationSetBy = Automatic

	partition FP = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [HR].[FP].*   FROM [HR].[FP]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"FP", "FP"}, {"FPDesc", "FPDesc"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"FP", type text}, {"FPDesc", type text}})
				in
				    #"Changed Type"

